# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
def set_hostname(server)
	server.vm.provision 'shell', inline: "hostname #{server.vm.hostname}"
end

Vagrant.configure("2") do |config|
	config.vm.define "vm1" do |n|
		n.vm.box = 'bento/centos-7.2'
		n.vm.box_version = '2.2.9'
		n.vm.hostname = 'vm1-centos'
		n.vm.network 'private_network', ip: '10.1.1.34'
		n.vm.network 'public_network', ip: '192.168.100.100'
		n.vm.network 'forwarded_port', guest: 9090, host: 9090
		set_hostname(n)
	end
end
